import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { Providers } from "./providers";

const montserrat = Montserrat({
	variable: "--font-montserrat",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`${montserrat.variable} h-full antialiased text-xs scrollbar-thin scrollbar-thumb-gray-300`}
		>
			<body className="min-h-screen flex flex-col">
				<Toaster position="bottom-center" />

				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
