import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { getCurrentUser } from "@/lib/auth/get-current-user";
import { TopBar } from "@/components/layouts/top-bar/top-bar";
import { MainSidebar } from "@/components/layouts/main-sidebar";

const montserrat = Montserrat({
	variable: "--font-montserrat",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const user = await getCurrentUser();

	return (
		<html
			lang="en"
			className={`${montserrat.variable} h-full antialiased text-xs`}
		>
			<body className="min-h-screen flex flex-col">
				<Toaster position="bottom-center" />

				<div className="min-h-screen flex flex-col">
					<TopBar user={user} />
					<div className="flex flex-1 min-h-0">
						{user && <MainSidebar />}
						<div className="flex-1 bg-gray-50">{children}</div>
					</div>
				</div>
			</body>
		</html>
	);
}
